spring.application.name=vocatio-api

# Configuración de la API
server.servlet.context-path=/api/v1
app.base-api-url=https://vocatio-api-latest.onrender.com
#PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://dpg-d4nqsj4hg0os739jveug-a.virginia-postgres.render.com:5432/vocatio_16rt
spring.datasource.username=vocatio_16rt_user
spring.datasource.password=YnXzOi9ttV07DHX5oL6GITXXuRDfLqx6
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seed de datos (habilitado por defecto)
app.seed.enabled=true

# JWT Configuration
jwt.secret=MiClaveSecretaSuperSeguraParaJWT123456789012345678901234567890
jwt.expiration=86400000
# 24 horas en milisegundos

#vocatio.openapi.dev-url=https://vocatio-api-latest.onrender.com/api/v1
